import pandas as pd
from datetime import datetime
import csv
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
#headers = ['DATE','TIME','VISALBEDOCAL','SWIRALBEDOCAL','TIRALBEDOCAL','CAMTEMPERATURE','SWIRTEMPERATURE','AMBTEMPERATURE','EXTTEMPERATURE','WDS/PIX','HDRWDS','XTABXLATE','YTABXLATE','GXPOS','GYPOS','GXLGTH','GXNO.','GYLGTH','GYNO.','FXLGTH','FROMDEPTH','TODEPTH','DEPTHINTERVAL','TRAYTYPE','WVLSTART','WVLEND','TOPVIS','XSPEED','PIXRATE','PIXMM','TOTINTSEC/PIX','BASEHT','PROFILPOSOFFSMM','PROFILRATIO','CAMPOSOFFSMM','CAMXFOVMM','CAMYFOVMM','CAMREFEDGE','CAMHT','YINCRCORE','COREHT','YWIDTH','XSTEPSIZE','TWDSPIX','THDRWDS','TIROFFSMM','TRAYTIM','FFOFFS','FCONSTANT','FROFFS','SPEEDCAL','XACCEL','TWVLST','TWVLEND','CASEID','TRAYTYPE.1','FILENAME','EXECUTABLE','COMMENT','LOGGER','SPECSERNO','SWVERSION','TRAYNOTE']

df = pd.read_csv('.\\out\\20210819_MRTalltest_aux9.csv',nrows=100)
print (df)
plt.scatter( df['SWIRALBEDOCAL'], df['VISALBEDOCAL'], s=df['SWIRTEMPERATURE'])
plt.xlabel('SWIRALBEDOCAL')
plt.ylabel('VISALBEDOCAL')
#plt.show()
plt.savefig('.\\out\\20210819_MRTalltest_aux9.png')